import { promises as fs, createReadStream, createWriteStream } from "fs";
import path from "path";
import crypto from "crypto";
import sharp from "sharp";
import { Readable } from "stream";
import { pipeline } from "stream/promises";
import { env } from "@/lib/env";

const STORAGE_ROOT = path.resolve(env.STORAGE_DIR);

export function userRoot(userId: string) {
  return path.join(STORAGE_ROOT, userId);
}

export function objectPath(userId: string, storageKey: string) {
  // storageKey is relative to the user root and was generated by us
  // (cuid()-based), so it's safe. We still resolve and validate.
  const full = path.resolve(userRoot(userId), storageKey);
  if (!full.startsWith(userRoot(userId) + path.sep) && full !== userRoot(userId)) {
    throw new Error("Ruta de almacenamiento no válida");
  }
  return full;
}

export async function ensureUserDir(userId: string) {
  await fs.mkdir(path.join(userRoot(userId), "files"), { recursive: true });
  await fs.mkdir(path.join(userRoot(userId), "thumbs"), { recursive: true });
}

export interface StoredFile {
  storageKey: string;
  size: number;
  checksum: string;
  thumbnailKey?: string;
  width?: number;
  height?: number;
}

/**
 * Streams a Web ReadableStream (e.g. from a multipart upload) to disk and
 * returns the metadata. Computes SHA-256 on the fly to avoid loading the
 * whole file in memory.
 */
export async function persistUpload(
  userId: string,
  fileId: string,
  webStream: ReadableStream<Uint8Array>,
  mimeType: string,
): Promise<StoredFile> {
  await ensureUserDir(userId);

  const ext = path.extname("").slice(0, 0); // we don't trust client extension
  const storageKey = path.posix.join("files", `${fileId}${ext}`);
  const fullPath = objectPath(userId, storageKey);

  const hash = crypto.createHash("sha256");
  let size = 0;

  const nodeStream = Readable.fromWeb(webStream as unknown as import("stream/web").ReadableStream<Uint8Array>);
  const writeStream = createWriteStream(fullPath);

  nodeStream.on("data", (chunk: Buffer) => {
    hash.update(chunk);
    size += chunk.length;
  });

  await pipeline(nodeStream, writeStream);

  const stored: StoredFile = {
    storageKey,
    size,
    checksum: hash.digest("hex"),
  };

  if (mimeType.startsWith("image/")) {
    try {
      const meta = await sharp(fullPath).metadata();
      stored.width = meta.width;
      stored.height = meta.height;

      const thumbKey = path.posix.join("thumbs", `${fileId}.webp`);
      await sharp(fullPath)
        .rotate()
        .resize(512, 512, { fit: "inside", withoutEnlargement: true })
        .webp({ quality: 80 })
        .toFile(objectPath(userId, thumbKey));
      stored.thumbnailKey = thumbKey;
    } catch {
      // ignore thumbnailing failures
    }
  }

  return stored;
}

export function readFileStream(userId: string, storageKey: string, range?: { start: number; end: number }) {
  const fullPath = objectPath(userId, storageKey);
  return createReadStream(fullPath, range);
}

export async function statObject(userId: string, storageKey: string) {
  return fs.stat(objectPath(userId, storageKey));
}

export async function removeObject(userId: string, storageKey: string) {
  try {
    await fs.unlink(objectPath(userId, storageKey));
  } catch (err: any) {
    if (err.code !== "ENOENT") throw err;
  }
}

export async function removeUserStorage(userId: string) {
  await fs.rm(userRoot(userId), { recursive: true, force: true });
}
